### ISSUE TITLE
Failure to correctly handle a paste in the middle of a biddingtable

### ISSUE THREAD

**Issue by palamau** [Kungsgeten/bml#2]
Fails on code such as
`2H Bal. 22--23/26+, 4/5!h (4!s poss.) OR 4!s + m rev. strength OR GF 4=4=(41)
    2S default action with most hands
        2N bal. 22/23 with 4/5!h
            #PASTE camlet_2N 
        3m natural, reversing strength hand with 4!s
        3!h/!s 4441 with short !c/!d`

[0001-Fix-bug-with-handling-PASTE-in-middle-of-bidtable.txt](https://github.com/Kungsgeten/bml/files/4673902/0001-Fix-bug-with-handling-PASTE-in-middle-of-bidtable.txt)

Attached a patch file that fixes the problem

**Comment by Kungsgeten** [comment]
Hi! I haven't used BML for some years and will probably not make any updates to the code. If you make a pull request though I can probably merge it.

**Comment by palamau** [comment]
The attached patch had a bug in it.  In any case, I have created a separate pull request

**Comment by palamau** [comment]
Made a pull request about 12 hours ago.

Thanks,
Rajendra
